server:
  port: ${port:9999}
  
spring:
  application:
    name: zuul-proxy-service

info:
  component: 'Zuul Proxy'

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
    
# route 규칙은 zuul.routes.[spring.application.name]=path
zuul:
  ignored-services: '*'
  ignored-patterns: { /**/api/**, /**/admin/** }
  routes:
    simple-service-with-discovery: 
      path: /hello/**
    simple-discovery-server: 
      path: /eureka/**
      #strip-prefix: false

## zuul default filter disable
#  SendErrorFilter:
#    error:
#      disable: true

# zuul custom filter disable
  EurekaRedirectPreFilter:
    pre:
      disable: true
  EurekaRedirectPostFilter:
    post:
      disable: false
  EurekaErrorRedirectFilter:
    post:
      disable: true
  ExampleErrorFilter:
    error:
      maxRetry: 3
      disable: true

eureka:
  instance:
    appname: zuul-proxy-testapp
    hostname: ${vcap.application.uris[0]:localhost}
    #non-secure-port: ${server.port}   # DO NOT USE NON-SECURE PORT WHEN IT USES EUREKA CLIENT
    #non-secure-port-enabled: true     # DO NOT USE NON-SECURE PORT WHEN IT USES EUREKA CLIENT
    metadata-map:
      instanceId: ${vcap.application.instance_id:${spring.application.name}-${eureka.instance.metadata-map.uuid}}
      uuid: ${random.uuid}
    lease-expiration-duration-in-seconds: 5 
    lease-renewal-interval-in-seconds: 10
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: ${zuul.eureka.client.enabled:true}
    
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
 
# https://docs.spring.io/spring-boot/docs/1.5.4.RELEASE/reference/htmlsingle/#production-ready-sensitive-endpoints
management:
  security:
    enabled: false
