server:
  port: ${port:9989}

info:
  component: 'Zuul Proxy (only Ribbon)'

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    enabled: true
    
# route 규칙은 zuul.routes.[spring.application.name]=path
zuul:
  ignored-services: '*'
  ignored-patterns: { /**/api/** }
  routes:
    simple-service-with-discovery: 
      serviceId: simple-service-with-discovery
      path: /hello/**
    simple-discovery-server:
      serviceId: simple-discovery-server
      path: /eureka/**
    simple-discovery-server-static:
      serviceId: simple-discovery-server
      path: /*/**
      
## zuul default filter disable
#  SendErrorFilter:
#    error:
#      disable: true

# zuul custom filter disable
  RequestMonitorFilter:
    pre:
      disable: false
  EurekaRedirectPostFilter:
    post:
      disable: true
  EurekaErrorRedirectFilter:
    post:
      disable: true
  ExampleErrorFilter:
    error:
      maxRetry: 3
      disable: true

eureka:
  client:
    enabled: false

ribbon:
  eureka:
    enabled: false
  ConnectTimeout: 3000
  ReadTimeout: 60000

simple-service-with-discovery:
    listOfServers: localhost:8988,localhost:8989
    ServerListRefreshInterval: 5000    

simple-discovery-server:
    listOfServers: localhost:8761
    ServerListRefreshInterval: 5000

# https://docs.spring.io/spring-boot/docs/1.5.4.RELEASE/reference/htmlsingle/#production-ready-sensitive-endpoints
management:
  security:
    enabled: false
